Write-Host "UBI Smart Contract Distributor setup"
Write-Host ""
Write-Host "1) Start MongoDB."
Write-Host "2) In blockchain/: npm install"
Write-Host "3) In blockchain/: npx hardhat compile"
Write-Host "4) Start a local chain: npx hardhat node"
Write-Host "5) Deploy in another terminal: npx hardhat run scripts/deploy.js --network localhost"
Write-Host "6) In backend/: npm install"
Write-Host "7) Copy .env.example to .env and set values."
Write-Host "8) Put the first Hardhat account private key into ADMIN_PRIVATE_KEY."
Write-Host "9) Start backend: npm run dev"
